### ISSUE TITLE
build panic on generating class

### ISSUE THREAD

**Issue by DK99** [google/autocxx#174]
## Expected Behavior
Successful build :)

## Actual Behavior
```
  thread 'main' panicked at 'expected identifier', /home/daniel/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-1.0.57/src/parse_quote.rs:96:21
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
     1: std::panicking::begin_panic_fmt
               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:437:5
     2: syn::parse_quote::parse
               at /home/daniel/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-1.0.57/src/parse_quote.rs:96:21
     3: autocxx_engine::conversion::parse::type_converter::TypeConverter::convert_type_path::{{closure}}
               at /home/daniel/.cargo/git/checkouts/autocxx-369cba6970eb5724/8b73ca1/engine/src/conversion/parse/type_converter.rs:148:30
     4: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
               at /home/daniel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:280:13
     5: core::option::Option<T>::map
               at /home/daniel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:453:29
     6: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::next
               at /home/daniel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:924:9
     7: <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::next
               at /home/daniel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/chain.rs:78:15
     8: <syn::punctuated::Punctuated<T,P> as core::iter::traits::collect::Extend<T>>::extend
               at /home/daniel/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-1.0.57/src/punctuated.rs:441:22
     9: <syn::punctuated::Punctuated<T,P> as core::iter::traits::collect::FromIterator<T>>::from_iter
               at /home/daniel/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-1.0.57/src/punctuated.rs:431:9
    10: core::iter::traits::iterator::Iterator::collect
               at /home/daniel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:1670:9
    11: autocxx_engine::conversion::parse::type_converter::TypeConverter::convert_type_path
               at /home/daniel/.cargo/git/checkouts/autocxx-369cba6970eb5724/8b73ca1/engine/src/conversion/parse/type_converter.rs:146:37
    12: autocxx_engine::conversion::parse::type_converter::TypeConverter::convert_type
               at /home/daniel/.cargo/git/checkouts/autocxx-369cba6970eb5724/8b73ca1/engine/src/conversion/parse/type_converter.rs:100:28
    13: autocxx_engine::conversion::parse::type_converter::TypeConverter::convert_boxed_type
               at /home/daniel/.cargo/git/checkouts/autocxx-369cba6970eb5724/8b73ca1/engine/src/conversion/parse/type_converter.rs:90:12
    14: autocxx_engine::conversion::parse::type_converter::TypeConverter::convert_ptr_to_reference
               at /home/daniel/.cargo/git/checkouts/autocxx-369cba6970eb5724/8b73ca1/engine/src/conversion/parse/type_converter.rs:265:20
    15: autocxx_engine::conversion::parse::type_converter::TypeConverter::convert_type
               at /home/daniel/.cargo/git/checkouts/autocxx-369cba6970eb5724/8b73ca1/engine/src/conversion/parse/type_converter.rs:126:31
    16: autocxx_engine::conversion::parse::type_converter::TypeConverter::convert_boxed_type
               at /home/daniel/.cargo/git/checkouts/autocxx-369cba6970eb5724/8b73ca1/engine/src/conversion/parse/type_converter.rs:90:12
    17: <autocxx_engine::conversion::parse::parse_bindgen::ParseBindgen as autocxx_engine::conversion::parse::parse_foreign_mod::ForeignModParseCallbacks>::convert_boxed_type
               at /home/daniel/.cargo/git/checkouts/autocxx-369cba6970eb5724/8b73ca1/engine/src/conversion/parse/parse_bindgen.rs:344:25
    18: autocxx_engine::conversion::parse::parse_foreign_mod::ParseForeignMod::convert_fn_arg
               at /home/daniel/.cargo/git/checkouts/autocxx-369cba6970eb5724/8b73ca1/engine/src/conversion/parse/parse_foreign_mod.rs:539:38
    19: autocxx_engine::conversion::parse::parse_foreign_mod::ParseForeignMod::convert_foreign_fn::{{closure}}
               at /home/daniel/.cargo/git/checkouts/autocxx-369cba6970eb5724/8b73ca1/engine/src/conversion/parse/parse_foreign_mod.rs:183:22
    20: core::iter::adapters::map_fold::{{closure}}
               at /home/daniel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:905:28
    21: core::iter::traits::iterator::Iterator::fold
               at /home/daniel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:2023:21
    22: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
               at /home/daniel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:945:9
    23: core::iter::traits::iterator::Iterator::partition
               at /home/daniel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:1723:9
    24: autocxx_engine::conversion::parse::parse_foreign_mod::ParseForeignMod::convert_foreign_fn
               at /home/daniel/.cargo/git/checkouts/autocxx-369cba6970eb5724/8b73ca1/engine/src/conversion/parse/parse_foreign_mod.rs:179:55
    25: autocxx_engine::conversion::parse::parse_foreign_mod::ParseForeignMod::finished
               at /home/daniel/.cargo/git/checkouts/autocxx-369cba6970eb5724/8b73ca1/engine/src/conversion/parse/parse_foreign_mod.rs:151:13
    26: autocxx_engine::conversion::parse::parse_bindgen::ParseBindgen::convert_mod_items
               at /home/daniel/.cargo/git/checkouts/autocxx-369cba6970eb5724/8b73ca1/engine/src/conversion/parse/parse_bindgen.rs:208:9
    27: autocxx_engine::conversion::parse::parse_bindgen::ParseBindgen::convert_mod_items
               at /home/daniel/.cargo/git/checkouts/autocxx-369cba6970eb5724/8b73ca1/engine/src/conversion/parse/parse_bindgen.rs:164:25
    28: autocxx_engine::conversion::parse::parse_bindgen::ParseBindgen::convert_items
               at /home/daniel/.cargo/git/checkouts/autocxx-369cba6970eb5724/8b73ca1/engine/src/conversion/parse/parse_bindgen.rs:106:9
    29: autocxx_engine::conversion::BridgeConverter::convert
               at /home/daniel/.cargo/git/checkouts/autocxx-369cba6970eb5724/8b73ca1/engine/src/conversion/mod.rs:81:37
    30: autocxx_engine::IncludeCppEngine::generate
               at /home/daniel/.cargo/git/checkouts/autocxx-369cba6970eb5724/8b73ca1/engine/src/lib.rs:303:26
    31: autocxx_engine::parse::ParsedFile::resolve_all
               at /home/daniel/.cargo/git/checkouts/autocxx-369cba6970eb5724/8b73ca1/engine/src/parse.rs:117:13
    32: autocxx_engine::builder::build_to_custom_directory
               at /home/daniel/.cargo/git/checkouts/autocxx-369cba6970eb5724/8b73ca1/engine/src/builder.rs:123:5
    33: autocxx_engine::builder::build
               at /home/daniel/.cargo/git/checkouts/autocxx-369cba6970eb5724/8b73ca1/engine/src/builder.rs:70:5
    34: autocxx_build::build
               at /home/daniel/.cargo/git/checkouts/autocxx-369cba6970eb5724/8b73ca1/gen/build/src/lib.rs:32:5
    35: build_script_build::main
               at ./build.rs:10:17
    36: core::ops::function::FnOnce::call_once
               at /home/daniel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

## Steps to Reproduce the Problem

1. I created a repository with my code https://github.com/DK99/prusaslicer_autocxx
1. Download it and execute the build.sh
1. Then just do a build and see the exception

## Specifications

- Version: 1.49.0
- Platform: Arch Linux

**Comment by adetaylor** [comment]
Thanks. Could you do any one of these things (in order of my preference!)

1. Narrow down which C++ construct is causing the problem, and raise a pull request to add a new test to `integration_tests.rs` :)
2. Build with `RUST_LOG=autocxx_engine=info` and add the logs here
3. Let me know where to find the C++ code it's trying to build

**Comment by DK99** [comment]
In regards to the first option I will take a look :)

Here are the additional logs:
```
cargo:warning=MESSAGE:Bindings: mod bindgen { /* automatically generated by rust-bindgen 0.56.1 */

  #[allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
  pub mod root {
      #[allow(unused_imports)]
      use self::super::root;
      pub type size_t = ::std::os::raw::c_ulong;
      #[repr(C)]
      pub struct __locale_struct {
          pub __locales: [*mut root::__locale_data; 13usize],
          pub __ctype_b: *const ::std::os::raw::c_ushort,
          pub __ctype_tolower: *const ::std::os::raw::c_int,
          pub __ctype_toupper: *const ::std::os::raw::c_int,
          pub __names: [*const ::std::os::raw::c_char; 13usize],
      }
      pub type __locale_t = *mut root::__locale_struct;
      pub type pthread_once_t = ::std::os::raw::c_int;
      pub type __gthread_once_t = root::pthread_once_t;
      pub type _Atomic_word = ::std::os::raw::c_int;
      pub mod __pstl {
          #[allow(unused_imports)]
          use self::super::super::root;
          pub mod execution {
              #[allow(unused_imports)]
              use self::super::super::super::root;
          }
      }
      pub mod boost {
          #[allow(unused_imports)]
          use self::super::super::root;
          pub mod detail {
              #[allow(unused_imports)]
              use self::super::super::super::root;
          }
          pub mod mpl {
              #[allow(unused_imports)]
              use self::super::super::super::root;
          }
          pub mod io {
              #[allow(unused_imports)]
              use self::super::super::super::root;
          }
          pub mod polygon {
              #[allow(unused_imports)]
              use self::super::super::super::root;
              pub mod detail {
                  #[allow(unused_imports)]
                  use self::super::super::super::super::root;
              }
          }
          pub mod iterators {
              #[allow(unused_imports)]
              use self::super::super::super::root;
          }
          pub mod concepts {
              #[allow(unused_imports)]
              use self::super::super::super::root;
          }
          pub mod algorithm {
              #[allow(unused_imports)]
              use self::super::super::super::root;
          }
          pub mod property_tree {
              #[allow(unused_imports)]
              use self::super::super::super::root;
          }
      }
      pub mod mpl_ {
          #[allow(unused_imports)]
          use self::super::super::root;
      }
      pub mod Slic3r {
          #[allow(unused_imports)]
          use self::super::super::root;
          #[repr(C)]
          pub struct clonable_ptr<T> {
              #[doc = "!< Native pointer"]
              pub px: *mut T,
              pub _phantom_0: ::std::marker::PhantomData<::std::cell::UnsafeCell<T>>,
          }
          #[doc = " The type of the managed object, aliased as member type"]
          pub type element_type<T> = T;
          pub type t_config_option_key = root::std::string;
          #[repr(u32)]
          #[derive(Copy, Clone, Hash, PartialEq, Eq)]
          pub enum ConfigOptionType {
              coVectorType = 16384,
              coNone = 0,
              coFloat = 1,
              coFloats = 16385,
              coInt = 2,
              coInts = 16386,
              coString = 3,
              coStrings = 16387,
              coPercent = 4,
              coPercents = 16388,
              coFloatOrPercent = 5,
              coFloatsOrPercents = 16389,
              coPoint = 6,
              coPoints = 16390,
              coPoint3 = 7,
              coBool = 8,
              coBools = 16392,
              coEnum = 9,
          }
          #[repr(u32)]
          #[derive(Copy, Clone, Hash, PartialEq, Eq)]
          pub enum ConfigOptionMode {
              comSimple = 0,
              comAdvanced = 1,
              comExpert = 2,
          }
          #[repr(u8)]
          #[derive(Copy, Clone, Hash, PartialEq, Eq)]
          pub enum PrinterTechnology {
              ptFFF = 0,
              ptSLA = 1,
              ptUnknown = 2,
              ptAny = 3,
          }
          #[repr(C)]
          pub struct ConfigOption__bindgen_vtable(::std::os::raw::c_void);
          #[repr(C)]
          pub struct ConfigOption {
              pub vtable_: *const ConfigOption__bindgen_vtable,
          }
          extern "C" {
              #[link_name = "\u{1}_ZNK6Slic3r12ConfigOption9is_scalarEv"]
              pub fn is_scalar(this: *const root::Slic3r::ConfigOption) -> bool;
          }
          extern "C" {
              #[link_name = "\u{1}_ZNK6Slic3r12ConfigOption9is_vectorEv"]
              pub fn is_vector(this: *const root::Slic3r::ConfigOption) -> bool;
          }
          impl ConfigOption {
              #[inline]
              pub unsafe fn is_scalar(&self) -> bool {
                  is_scalar(self)
              }
              #[inline]
              pub unsafe fn is_vector(&self) -> bool {
                  is_vector(self)
              }
          }
          extern "C" {
              #[link_name = "\u{1}_ZN6Slic3r12ConfigOptionD1Ev"]
              pub fn ConfigOption_destructor(this: *mut root::Slic3r::ConfigOption);
          }
          extern "C" {
              #[link_name = "\u{1}_ZNK6Slic3r12ConfigOption6getIntEv"]
              pub fn getInt(this: *mut ::std::os::raw::c_void) -> ::std::os::raw::c_int;
          }
          extern "C" {
              #[link_name = "\u{1}_ZNK6Slic3r12ConfigOption8getFloatEv"]
              pub fn getFloat(this: *mut ::std::os::raw::c_void) -> f64;
          }
          extern "C" {
              #[link_name = "\u{1}_ZNK6Slic3r12ConfigOption7getBoolEv"]
              pub fn getBool(this: *mut ::std::os::raw::c_void) -> bool;
          }
          extern "C" {
              #[link_name = "\u{1}_ZN6Slic3r12ConfigOption6setIntEi"]
              pub fn setInt(this: *mut ::std::os::raw::c_void, arg1: ::std::os::raw::c_int);
          }
          extern "C" {
              #[link_name = "\u{1}_ZNK6Slic3r12ConfigOption8nullableEv"]
              pub fn nullable(this: *mut ::std::os::raw::c_void) -> bool;
          }
          extern "C" {
              #[link_name = "\u{1}_ZNK6Slic3r12ConfigOption6is_nilEv"]
              pub fn is_nil(this: *mut ::std::os::raw::c_void) -> bool;
          }
          extern "C" {
              #[link_name = "\u{1}_ZNK6Slic3r12ConfigOption12overriden_byEPKS0_"]
              pub fn overriden_by(
                  this: *mut ::std::os::raw::c_void,
                  rhs: *const root::Slic3r::ConfigOption,
              ) -> bool;
          }
          extern "C" {
              #[link_name = "\u{1}_ZN6Slic3r12ConfigOption14apply_overrideEPKS0_"]
              pub fn apply_override(
                  this: *mut ::std::os::raw::c_void,
                  rhs: *const root::Slic3r::ConfigOption,
              ) -> bool;
          }
          pub type t_config_enum_values = root::std::map<
              root::std::string,
              ::std::os::raw::c_int,
              root::std::less<
                  root::std::basic_string<
                      ::std::os::raw::c_char,
                      root::std::char_traits<::std::os::raw::c_char>,
                      root::std::allocator<::std::os::raw::c_char>,
                  >,
              >,
              root::std::allocator<
                  root::std::pair<
                      root::std::basic_string<
                          ::std::os::raw::c_char,
                          root::std::char_traits<::std::os::raw::c_char>,
                          root::std::allocator<::std::os::raw::c_char>,
                      >,
                      ::std::os::raw::c_int,
                  >,
              >,
          >;
          #[repr(C)]
          pub struct ConfigOptionDef {
              pub opt_key: root::Slic3r::t_config_option_key,
              pub type_: root::Slic3r::ConfigOptionType,
              pub nullable: bool,
              pub default_value: root::Slic3r::clonable_ptr<root::Slic3r::ConfigOption>,
              pub gui_type: root::std::string,
              pub __bindgen_padding_0: [u64; 3usize],
              pub gui_flags: root::std::string,
              pub __bindgen_padding_1: [u64; 3usize],
              pub label: root::std::string,
              pub __bindgen_padding_2: [u64; 3usize],
              pub full_label: root::std::string,
              pub __bindgen_padding_3: [u8; 24usize],
              pub printer_technology: root::Slic3r::PrinterTechnology,
              pub category: root::std::string,
              pub __bindgen_padding_4: [u64; 3usize],
              pub tooltip: root::std::string,
              pub __bindgen_padding_5: [u64; 3usize],
              pub sidetext: root::std::string,
              pub __bindgen_padding_6: [u64; 3usize],
              pub cli: root::std::string,
              pub __bindgen_padding_7: [u64; 3usize],
              pub ratio_over: root::Slic3r::t_config_option_key,
              pub multiline: bool,
              pub full_width: bool,
              pub is_code: bool,
              pub readonly: bool,
              pub height: ::std::os::raw::c_int,
              pub width: ::std::os::raw::c_int,
              pub min: ::std::os::raw::c_int,
              pub max: ::std::os::raw::c_int,
              pub mode: root::Slic3r::ConfigOptionMode,
              pub aliases: root::std::vector<root::Slic3r::t_config_option_key>,
              pub shortcut: root::std::vector<root::Slic3r::t_config_option_key>,
              pub enum_values: root::std::vector<root::std::string>,
              pub enum_labels: root::std::vector<root::std::string>,
              pub enum_keys_map: *const root::Slic3r::t_config_enum_values,
              pub serialization_key_ordinal: root::size_t,
          }
          pub const nocli: &'static [u8; 9usize] = b"~~~noCLI\0";
          extern "C" {
              #[link_name = "\u{1}_ZN6Slic3r15ConfigOptionDef17set_default_valueEPKNS_12ConfigOptionE"]
              pub fn set_default_value(
                  this: *mut root::Slic3r::ConfigOptionDef,
                  ptr: *const root::Slic3r::ConfigOption,
              );
          }
          extern "C" {
              #[link_name = "\u{1}_ZNK6Slic3r15ConfigOptionDef19create_empty_optionEv"]
              pub fn create_empty_option(
                  this: *const root::Slic3r::ConfigOptionDef,
              ) -> *mut root::Slic3r::ConfigOption;
          }
          extern "C" {
              #[link_name = "\u{1}_ZNK6Slic3r15ConfigOptionDef21create_default_optionEv"]
              pub fn create_default_option(
                  this: *const root::Slic3r::ConfigOptionDef,
              ) -> *mut root::Slic3r::ConfigOption;
          }
          extern "C" {
              #[link_name = "\u{1}_ZNK6Slic3r15ConfigOptionDef14has_enum_valueERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE"]
              pub fn has_enum_value(
                  this: *const root::Slic3r::ConfigOptionDef,
                  value: *const root::std::string,
              ) -> bool;
          }
          extern "C" {
              #[link_name = "\u{1}_ZNK6Slic3r15ConfigOptionDef8cli_argsERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE"]
              pub fn cli_args(
                  this: *const root::Slic3r::ConfigOptionDef,
                  key: *const root::std::string,
              ) -> root::std::vector<root::std::string>;
          }
          impl ConfigOptionDef {
              #[inline]
              pub unsafe fn set_default_value(&mut self, ptr: *const root::Slic3r::ConfigOption) {
                  set_default_value(self, ptr)
              }
              #[inline]
              pub unsafe fn create_empty_option(&self) -> *mut root::Slic3r::ConfigOption {
                  create_empty_option(self)
              }
              #[inline]
              pub unsafe fn create_default_option(&self) -> *mut root::Slic3r::ConfigOption {
                  create_default_option(self)
              }
              #[inline]
              pub unsafe fn has_enum_value(&self, value: *const root::std::string) -> bool {
                  has_enum_value(self, value)
              }
              #[inline]
              pub unsafe fn cli_args(
                  &self,
                  key: *const root::std::string,
              ) -> root::std::vector<root::std::string> {
                  cli_args(self, key)
              }
          }
          pub type t_optiondef_map = root::std::map<
              root::Slic3r::t_config_option_key,
              root::Slic3r::ConfigOptionDef,
              root::std::less<
                  root::std::basic_string<
                      ::std::os::raw::c_char,
                      root::std::char_traits<::std::os::raw::c_char>,
                      root::std::allocator<::std::os::raw::c_char>,
                  >,
              >,
              root::std::allocator<
                  root::std::pair<
                      root::std::basic_string<
                          ::std::os::raw::c_char,
                          root::std::char_traits<::std::os::raw::c_char>,
                          root::std::allocator<::std::os::raw::c_char>,
                      >,
                      root::Slic3r::ConfigOptionDef,
                  >,
              >,
          >;
          #[repr(C)]
          pub struct ConfigDef {
              pub options: root::Slic3r::t_optiondef_map,
              pub by_serialization_key_ordinal: root::std::map<
                  root::size_t,
                  *const root::Slic3r::ConfigOptionDef,
                  root::std::less<::std::os::raw::c_ulong>,
                  root::std::allocator<
                      root::std::pair<::std::os::raw::c_ulong, *const root::Slic3r::ConfigOptionDef>,
                  >,
              >,
          }
          extern "C" {
              #[link_name = "\u{1}_ZNK6Slic3r9ConfigDef3hasERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE"]
              pub fn has(
                  this: *const root::Slic3r::ConfigDef,
                  opt_key: *const root::Slic3r::t_config_option_key,
              ) -> bool;
          }
          extern "C" {
              #[link_name = "\u{1}_ZNK6Slic3r9ConfigDef3getERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE"]
              pub fn get(
                  this: *const root::Slic3r::ConfigDef,
                  opt_key: *const root::Slic3r::t_config_option_key,
              ) -> *const root::Slic3r::ConfigOptionDef;
          }
          extern "C" {
              #[link_name = "\u{1}_ZNK6Slic3r9ConfigDef4keysB5cxx11Ev"]
              pub fn keys(
                  this: *const root::Slic3r::ConfigDef,
              ) -> root::std::vector<root::std::string>;
          }
          extern "C" {
              #[doc = " Iterate through all of the CLI options and write them to a stream."]
              #[link_name = "\u{1}_ZNK6Slic3r9ConfigDef14print_cli_helpERSobSt8functionIFbRKNS_15ConfigOptionDefEEE"]
              pub fn print_cli_help(
                  this: *const root::Slic3r::ConfigDef,
                  out: *mut root::std::ostream,
                  show_defaults: bool,
                  filter: [u64; 4usize],
              ) -> *mut root::std::ostream;
          }
          extern "C" {
              #[link_name = "\u{1}_ZN6Slic3r9ConfigDef3addERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_16ConfigOptionTypeE"]
              pub fn add(
                  this: *mut root::Slic3r::ConfigDef,
                  opt_key: *const root::Slic3r::t_config_option_key,
                  type_: root::Slic3r::ConfigOptionType,
              ) -> *mut root::Slic3r::ConfigOptionDef;
          }
          extern "C" {
              #[link_name = "\u{1}_ZN6Slic3r9ConfigDef12add_nullableERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_16ConfigOptionTypeE"]
              pub fn add_nullable(
                  this: *mut root::Slic3r::ConfigDef,
                  opt_key: *const root::Slic3r::t_config_option_key,
                  type_: root::Slic3r::ConfigOptionType,
              ) -> *mut root::Slic3r::ConfigOptionDef;
          }
          impl ConfigDef {
              #[inline]
              pub unsafe fn has(&self, opt_key: *const root::Slic3r::t_config_option_key) -> bool {
                  has(self, opt_key)
              }
              #[inline]
              pub unsafe fn get(
                  &self,
                  opt_key: *const root::Slic3r::t_config_option_key,
              ) -> *const root::Slic3r::ConfigOptionDef {
                  get(self, opt_key)
              }
              #[inline]
              pub unsafe fn keys(&self) -> root::std::vector<root::std::string> {
                  keys(self)
              }
              #[inline]
              pub unsafe fn print_cli_help(
                  &self,
                  out: *mut root::std::ostream,
                  show_defaults: bool,
                  filter: [u64; 4usize],
              ) -> *mut root::std::ostream {
                  print_cli_help(self, out, show_defaults, filter)
              }
              #[inline]
              pub unsafe fn add(
                  &mut self,
                  opt_key: *const root::Slic3r::t_config_option_key,
                  type_: root::Slic3r::ConfigOptionType,
              ) -> *mut root::Slic3r::ConfigOptionDef {
                  add(self, opt_key, type_)
              }
              #[inline]
              pub unsafe fn add_nullable(
                  &mut self,
                  opt_key: *const root::Slic3r::t_config_option_key,
                  type_: root::Slic3r::ConfigOptionType,
              ) -> *mut root::Slic3r::ConfigOptionDef {
                  add_nullable(self, opt_key, type_)
              }
          }
          #[repr(C)]
          pub struct PrintConfigDef {
              pub _base: root::Slic3r::ConfigDef,
              pub m_extruder_option_keys: root::std::vector<root::std::string>,
              pub m_extruder_retract_keys: root::std::vector<root::std::string>,
          }
          extern "C" {
              #[link_name = "\u{1}_ZN6Slic3r14PrintConfigDef13handle_legacyERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_"]
              pub fn handle_legacy(
                  opt_key: *mut root::Slic3r::t_config_option_key,
                  value: *mut root::std::string,
              );
          }
          extern "C" {
              #[link_name = "\u{1}_ZNK6Slic3r14PrintConfigDef20extruder_option_keysB5cxx11Ev"]
              pub fn extruder_option_keys(
                  this: *const root::Slic3r::PrintConfigDef,
              ) -> *const root::std::vector<root::std::string>;
          }
          extern "C" {
              #[link_name = "\u{1}_ZNK6Slic3r14PrintConfigDef21extruder_retract_keysB5cxx11Ev"]
              pub fn extruder_retract_keys(
                  this: *const root::Slic3r::PrintConfigDef,
              ) -> *const root::std::vector<root::std::string>;
          }
          extern "C" {
              #[link_name = "\u{1}_ZN6Slic3r14PrintConfigDefC1Ev"]
              pub fn PrintConfigDef(this: *mut root::Slic3r::PrintConfigDef);
          }
          impl PrintConfigDef {
              #[inline]
              pub unsafe fn handle_legacy(
                  opt_key: *mut root::Slic3r::t_config_option_key,
                  value: *mut root::std::string,
              ) {
                  handle_legacy(opt_key, value)
              }
              #[inline]
              pub unsafe fn extruder_option_keys(
                  &self,
              ) -> *const root::std::vector<root::std::string> {
                  extruder_option_keys(self)
              }
              #[inline]
              pub unsafe fn extruder_retract_keys(
                  &self,
              ) -> *const root::std::vector<root::std::string> {
                  extruder_retract_keys(self)
              }
              #[inline]
              pub unsafe fn new() -> Self {
                  let mut __bindgen_tmp = ::std::mem::MaybeUninit::uninit();
                  PrintConfigDef(__bindgen_tmp.as_mut_ptr());
                  __bindgen_tmp.assume_init()
              }
          }
      }
      pub mod Eigen {
          #[allow(unused_imports)]
          use self::super::super::root;
          pub mod internal {
              #[allow(unused_imports)]
              use self::super::super::super::root;
          }
      }
      pub mod cereal {
          #[allow(unused_imports)]
          use self::super::super::root;
          pub mod detail {
              #[allow(unused_imports)]
              use self::super::super::super::root;
          }
          pub mod traits {
              #[allow(unused_imports)]
              use self::super::super::super::root;
          }
      }
      pub mod boost_concepts {
          #[allow(unused_imports)]
          use self::super::super::root;
      }
      #[repr(C)]
      pub struct __locale_data {
          pub _address: u8,
      }
  }
   }
  cargo:warning=MESSAGE:Converting "std::os::raw::c_void"
  thread 'main' panicked at 'expected identifier', /home/daniel/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-1.0.57/src/parse_quote.rs:96:21
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The C++ code is in this repository https://github.com/prusa3d/PrusaSlicer
But it is much easier if you look at my repository there I have nothing else except the autocxx trying to build the C++ repo. I also had to bump the C++ version from 14 to 17 inside the autocxx code

**Comment by adetaylor** [comment]
Thanks!

Here's what's happening. `bindgen` is processing the Prusa C++ headers and outputting the bindings which you've kindly listed in the output above. `autocxx` is trying to convert those bindings to a form suitable for `cxx` and is exploding on _something_ in there. That's why I needed the C++ as well as the Rust.

I will work out what's going wrong. Expect that to take a few days because I currently don't have a test framework which enables the code to accept `bindgen` output in that form - it'll be useful to add it though.

To set expectations, `autocxx` has hardly been used _at all_ against real C++ codebases yet. In fact it's only been ever used against Chromium code. I expect that use against a different real codebase, including boost, will throw up five or six different issues I'll need to fix.

Thanks for doing this! It's much appreciated to have folks try it against real codebases and find lots of things to fix.

**Comment by adetaylor** [comment]
Status here: I've fixed this so that `autocxx` no longer chokes on the code in your particular example.

It will now happily _ignore_ all the code in that file.

But that's not the same as saying it will successfully _generate_ bindings for any of it. I haven't used your repo and therefore haven't used the `generate!("Slic3r::PrintConfigDef")` directive that you put in there.

My guess is, you'll immediately run into #179. But _maybe_ it will ignore those methods that and you'd be able to call something like:

```rust
use ffi::ToCppString;
let mut cfg = ffi::Slic3r::PrintConfigDef::make_unique();
cfg.pin_mut().handle_legacy("legacy-key".to_cpp());
```

since that's the only method on this class which doesn't require `std::vector`.

I still think we'll have a couple more problems to resolve before even the above works. Let me know how you get on.

If you'd like me to dig a bit more, please could you adjust your repo so that it will fetch and put the prusa source (and any other dependencies, e.g. boost??) in the right place using git submodules? (even though they're horrid, that will guarantee I get just the right versions in just the right directories with a simple `git submodule update --init --recursive`.)

**Comment by DK99** [comment]
First of all thank you for your effort.
The build panic is gone but now I have a different issue

```rust
error[E0433]: failed to resolve: could not find `std` in `root`
 --> /home/daniel/cups/prusaslicer_autocxx/target/debug/build/prusaslicer_autocxx-d1ec6ae45b10528f/out/autocxx-build/rs/16149805911353259661.rs:1:713
  |
1 | ...8 ; 0] , } pub type t_config_option_key = root :: std :: string ; impl PrintConfigDef { pub fn handle_legacy (opt_key : Pin < & mut Cx...
  |                                                      ^^^ could not find `std` in `root`

error: aborting due to previous error
```
I will try to put something together with all the necessary dependencies. I will probably build a Dockerfile as some dependencies e.g. boost are very large and it would be a pain to build them.

**Comment by DK99** [comment]
I created a Dockerfile in my repo with which you can easily reproduce my errors.

**Comment by adetaylor** [comment]
Thanks, I raised #183 for that issue.

**Comment by adetaylor** [comment]
OK, I fixed a couple of issues so you ought to be able to get further now. Thanks very much for putting together your Dockerfile; I haven't had a chance to try it out yet, but I nevertheless think I've fixed the problems discussed above so far. I'm sure there will be more - thanks again for your willingness to work through and report issues when trying this out with real code!
