### ISSUE TITLE
"Type was unexpectedly annotated"

### ISSUE THREAD

**Issue by adetaylor** [google/autocxx#222]
In trying to craft a test case for #216 I came across a different error:

```
thread 'integration_tests::test_bindgen_makes_opaque' panicked at 'Type was unexpectedly annotated', /Users/adetaylor/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.57.0/src/codegen/mod.rs:3439:13
stack backtrace:
   0: std::panicking::begin_panic
             at /Users/adetaylor/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:519:12
   1: autocxx_bindgen::codegen::RustTy::unwrap_ts
             at /Users/adetaylor/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.57.0/src/codegen/mod.rs:3439:13
   2: <autocxx_bindgen::ir::ty::Type as autocxx_bindgen::codegen::CodeGenerator>::codegen::{{closure}}
             at /Users/adetaylor/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.57.0/src/codegen/mod.rs:812:35
   3: core::result::Result<T,E>::map
             at /Users/adetaylor/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:504:25
   4: <autocxx_bindgen::ir::ty::Type as autocxx_bindgen::codegen::CodeGenerator>::codegen
             at /Users/adetaylor/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.57.0/src/codegen/mod.rs:810:40
   5: <autocxx_bindgen::ir::item::Item as autocxx_bindgen::codegen::CodeGenerator>::codegen
             at /Users/adetaylor/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.57.0/src/codegen/mod.rs:477:17
   6: <autocxx_bindgen::ir::comp::CompInfo as autocxx_bindgen::codegen::CodeGenerator>::codegen
             at /Users/adetaylor/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.57.0/src/codegen/mod.rs:1995:13
   7: <autocxx_bindgen::ir::ty::Type as autocxx_bindgen::codegen::CodeGenerator>::codegen
             at /Users/adetaylor/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.57.0/src/codegen/mod.rs:769:39
   8: <autocxx_bindgen::ir::item::Item as autocxx_bindgen::codegen::CodeGenerator>::codegen
             at /Users/adetaylor/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.57.0/src/codegen/mod.rs:477:17
   9: <autocxx_bindgen::ir::module::Module as autocxx_bindgen::codegen::CodeGenerator>::codegen::{{closure}}
             at /Users/adetaylor/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.57.0/src/codegen/mod.rs:499:21
  10: <autocxx_bindgen::ir::module::Module as autocxx_bindgen::codegen::CodeGenerator>::codegen::{{closure}}
             at /Users/adetaylor/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.57.0/src/codegen/mod.rs:547:13
  11: autocxx_bindgen::codegen::CodegenResult::inner
             at /Users/adetaylor/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.57.0/src/codegen/mod.rs:318:9
  12: <autocxx_bindgen::ir::module::Module as autocxx_bindgen::codegen::CodeGenerator>::codegen
             at /Users/adetaylor/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.57.0/src/codegen/mod.rs:534:27
  13: <autocxx_bindgen::ir::item::Item as autocxx_bindgen::codegen::CodeGenerator>::codegen
             at /Users/adetaylor/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.57.0/src/codegen/mod.rs:468:17
  14: autocxx_bindgen::codegen::codegen::{{closure}}
             at /Users/adetaylor/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.57.0/src/codegen/mod.rs:4212:9
  15: autocxx_bindgen::ir::context::BindgenContext::gen
             at /Users/adetaylor/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.57.0/src/ir/context.rs:1159:19
  16: autocxx_bindgen::codegen::codegen
             at /Users/adetaylor/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.57.0/src/codegen/mod.rs:4186:5
  17: autocxx_bindgen::Bindings::generate
             at /Users/adetaylor/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.57.0/src/lib.rs:2207:32
  18: autocxx_bindgen::Builder::generate
             at /Users/adetaylor/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.57.0/src/lib.rs:1380:9
  19: autocxx_engine::IncludeCppEngine::generate
             at ./src/lib.rs:404:24
  20: autocxx_engine::parse_file::ParsedFile::resolve_all
             at ./src/parse_file.rs:125:13
  21: autocxx_engine::builder::build_to_custom_directory
             at ./src/builder.rs:136:5
  22: autocxx_engine::integration_tests::do_run_test
             at ./src/integration_tests.rs:226:25
  23: autocxx_engine::integration_tests::run_test
             at ./src/integration_tests.rs:110:5
  24: autocxx_engine::integration_tests::test_bindgen_makes_opaque::test_impl
             at ./src/integration_tests.rs:3662:5
  25: autocxx_engine::integration_tests::test_bindgen_makes_opaque
             at ./src/integration_tests.rs:3598:1
  26: autocxx_engine::integration_tests::test_bindgen_makes_opaque::{{closure}}
             at ./src/integration_tests.rs:3598:1
  27: core::ops::function::FnOnce::call_once
             at /Users/adetaylor/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  28: core::ops::function::FnOnce::call_once
             at /rustc/e9920ef7749d11fc71cc32ca4ba055bcfeaab945/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    integration_tests::test_bindgen_makes_opaque
```

This is similar to #217.

**Comment by adetaylor** [comment]
In fact, this _is_ the first of the two problems listed in #217.

**Comment by lovasoa** [comment]
I'm currently trying to bind Google OR-Tools with autocxx and I'm getting this error : 

```
  --- stderr
  thread 'main' panicked at 'Type was unexpectedly annotated', /home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.57.1/src/codegen/mod.rs:3439:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Is it just that the fix hasn't been published to crates.io yet ?

**Comment by adetaylor** [comment]
That's probable yes. Could you let me know:
* the version number of `autocxx` that you've ended up with
* the full output when you run it with the environment variable `RUST_LOG=autocxx_engine=info`

Thanks!
To set expectations, `autocxx` is not yet battle-hardened. Each time we try it with a new C++ codebase, we encounter some new issues that need fixing. I do endeavour to get them fixed as soon as possible though, because it's incredibly valuable to get this real-world testing - so thanks for taking the plunge! Hopefully, with your log output as above, I should be able to spot any problems that are going to occur further down the line.

**Comment by lovasoa** [comment]
I was using autocxx 0.5..

```
 RUST_BACKTRACE=1 RUST_LOG=autocxx_engine=info cargo build >/tmp/stdout.txt 2>/tmp/stderr.txt
````

[stderr.txt](https://github.com/google/autocxx/files/6150163/stderr.txt)

**Comment by lovasoa** [comment]
If you want to reproduce that, you can download google OR tools there: https://github.com/google/or-tools/releases/tag/v8.2

**Comment by adetaylor** [comment]
Thanks, could you attach `stdout.txt` too?

**Comment by lovasoa** [comment]
stdout.txt is empty

**Comment by adetaylor** [comment]
OK, I reproduced your problem in #260. (In future it'd be great if you can upload a complete reproducible test case to a new issue, it took me about 60 minutes to figure out how to install ortools and feed it to autocxx!) I've not had a chance to look into the actual _bug_ yet - I'll do that later - but I can confirm it still applies on up-to-date autocxx code. Thanks again for spotting it!

**Comment by lovasoa** [comment]
Oh, sorry, you should have asked ! I would have uploaded my code.
