### ISSUE TITLE
Static constants are not ignored if they're inside a type

### ISSUE THREAD

**Issue by adetaylor** [google/autocxx#262]
`bindgen` gave us this:

```rust
                  extern "C" {
                      #[link_name = "\u{1}_ZN6google8protobuf8internal15ThreadSafeArena23lifecycle_id_generator_E"]
                      pub static mut lifecycle_id_generator_:
                          root::google::protobuf::internal::CacheAlignedLifecycleIdGenerator;
                  }
```

resulting in

```
 thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnexpectedForeignItem', engine/src/conversion/parse/parse_bindgen.rs:104:29
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/3f5aee2d5241139d808f4fdece0026603489afd1/library/std/src/panicking.rs:493:5
     1: core::panicking::panic_fmt
               at /rustc/3f5aee2d5241139d808f4fdece0026603489afd1/library/core/src/panicking.rs:92:14
     2: core::option::expect_none_failed
               at /rustc/3f5aee2d5241139d808f4fdece0026603489afd1/library/core/src/option.rs:1300:5
     3: core::result::Result<T,E>::unwrap
               at /rustc/3f5aee2d5241139d808f4fdece0026603489afd1/library/core/src/result.rs:1037:23
     4: autocxx_engine::conversion::parse::parse_bindgen::ParseBindgen::parse_mod_items
               at /usr/local/google/home/adetaylor/autocxx/engine/src/conversion/parse/parse_bindgen.rs:104:27
     5: autocxx_engine::conversion::parse::parse_bindgen::ParseBindgen::parse_item
               at /usr/local/google/home/adetaylor/autocxx/engine/src/conversion/parse/parse_bindgen.rs:156:21
     6: autocxx_engine::conversion::parse::parse_bindgen::ParseBindgen::parse_mod_items
               at /usr/local/google/home/adetaylor/autocxx/engine/src/conversion/parse/parse_bindgen.rs:99:21
     7: autocxx_engine::conversion::parse::parse_bindgen::ParseBindgen::parse_item
               at /usr/local/google/home/adetaylor/autocxx/engine/src/conversion/parse/parse_bindgen.rs:156:21
     8: autocxx_engine::conversion::parse::parse_bindgen::ParseBindgen::parse_mod_items
               at /usr/local/google/home/adetaylor/autocxx/engine/src/conversion/parse/parse_bindgen.rs:99:21
     9: autocxx_engine::conversion::parse::parse_bindgen::ParseBindgen::parse_item
               at /usr/local/google/home/adetaylor/autocxx/engine/src/conversion/parse/parse_bindgen.rs:156:21
    10: autocxx_engine::conversion::parse::parse_bindgen::ParseBindgen::parse_mod_items
               at /usr/local/google/home/adetaylor/autocxx/engine/src/conversion/parse/parse_bindgen.rs:99:21
    11: autocxx_engine::conversion::parse::parse_bindgen::ParseBindgen::parse_items
               at /usr/local/google/home/adetaylor/autocxx/engine/src/conversion/parse/parse_bindgen.rs:70:9
    12: autocxx_engine::conversion::BridgeConverter::convert
               at /usr/local/google/home/adetaylor/autocxx/engine/src/conversion/mod.rs:91:37
    13: autocxx_engine::IncludeCppEngine::generate
               at /usr/local/google/home/adetaylor/autocxx/engine/src/lib.rs:395:26
    14: autocxx_engine::parse_file::ParsedFile::resolve_all
               at /usr/local/google/home/adetaylor/autocxx/engine/src/parse_file.rs:125:13
    15: autocxx_engine::builder::build_to_custom_directory
               at /usr/local/google/home/adetaylor/autocxx/engine/src/builder.rs:136:5
    16: autocxx_engine::builder::build
               at /usr/local/google/home/adetaylor/autocxx/engine/src/builder.rs:75:5
    17: autocxx_build::build
               at /usr/local/google/home/adetaylor/autocxx/gen/build/src/lib.rs:33:5
    18: build_script_build::main
               at ./build.rs:23:17
    19: core::ops::function::FnOnce::call_once
               at /rustc/3f5aee2d5241139d808f4fdece0026603489afd1/library/core/src/ops/function.rs:227:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

No reproduction instructions yet because I haven't minimized the test case.

**Comment by adetaylor** [comment]
[This is probably the sort of code which caused this](https://git.xkool.org/hw/protobuf/-/blob/4cd56bdef81527df885d7fd408f40cdc71149c36/src/google/protobuf/arena_impl.h#L450).
