### ISSUE TITLE
thread 'main' panicked at 'Not an item: ItemId(40063)'

### ISSUE THREAD

**Issue by milahu** [google/autocxx#779]
testing autocxx with `llvm` and `clang`

trying to implement clang's [pp-trace](https://clang.llvm.org/extra/doxygen/PPTrace_8cpp_source.html) in rust

## Expected Behavior

should "just work"

## Actual Behavior

```
$ RUST_BACKTRACE=full cargo build 
   Compiling nix-build-incremental-experiments v0.1.0 (/home/user/src/nixos/nix-ccache/nix-build-incremental/nix-build-incremental-experiments)
error: failed to run custom build command for `nix-build-incremental-experiments v0.1.0 (/home/user/src/nixos/nix-ccache/nix-build-incremental/nix-build-incremental-experiments)`

Caused by:
  process didn't exit successfully: `/home/user/src/nixos/nix-ccache/nix-build-incremental/nix-build-incremental-experiments/target/debug/build/nix-build-incremental-experiments-fd2f3191fb4500a9/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=/home/user/src/nixos/nix-ccache/nix-build-incremental/nix-build-incremental-experiments/clang/Tooling/CommonOptionsParser.h
  cargo:rerun-if-changed=/nix/store/x5s3qmy7pnwyk7n7ypr556ns92jrxkkz-clang-10.0.1-dev/include/clang/Tooling/ArgumentsAdjusters.h

[ ... ]

  cargo:rerun-if-changed=/nix/store/mck6a026qp4ydzkz9wn6ww2npnjmidlx-llvm-10.0.1-dev/include/llvm/Support/ReverseIteration.h
  cargo:rerun-if-changed=/nix/store/mck6a026qp4ydzkz9wn6ww2npnjmidlx-llvm-10.0.1-dev/include/llvm/Support/ManagedStatic.h

  --- stderr
  thread 'main' panicked at 'Not an item: ItemId(40063)', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.59.13/src/ir/context.rs:1464:21
```

<details>
<summary>trace</summary>

```
  stack backtrace:
     0:     0x55abe97b5726 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1ef07120adb99796
     1:     0x55abe97ccc0c - core::fmt::write::h59cc4b3dea155cce
     2:     0x55abe979f445 - std::io::Write::write_fmt::he7e4fb4b70c5207a
     3:     0x55abe97ab930 - std::panicking::default_hook::{{closure}}::h67c88fba3a1757d9
     4:     0x55abe97ab4d1 - std::panicking::default_hook::had51536d17f32530
     5:     0x55abe97abee3 - std::panicking::rust_panic_with_hook::hcdfd560c4f6afa56
     6:     0x55abe97b5c10 - std::panicking::begin_panic_handler::{{closure}}::h5e7abb77afe4762c
     7:     0x55abe97b5874 - std::sys_common::backtrace::__rust_end_short_backtrace::hb15a1d01c910931c
     8:     0x55abe97aba22 - rust_begin_unwind
     9:     0x55abe8ca67fb - std::panicking::begin_panic_fmt::ha0cdca991725ff2b
    10:     0x55abe91e8a79 - autocxx_bindgen::ir::context::BindgenContext::resolve_item::h5734223ff6c1d749
                                 at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.59.13/src/ir/context.rs:1464:21
    11:     0x55abe91e8504 - autocxx_bindgen::ir::context::BindgenContext::resolve_type::hd747449bc67d9b1e
                                 at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.59.13/src/ir/context.rs:1428:9
    12:     0x55abe90ff776 - autocxx_bindgen::ir::ty::Type::layout::{{closure}}::hf92a0fb3944b649d
                                 at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.59.13/src/ir/ty.rs:232:21
    13:     0x55abe9146487 - core::option::Option<T>::or_else::h4e33cf5988a6bdb5
                                 at /build/rustc-1.56.1-src/library/core/src/option.rs:1137:21
    14:     0x55abe90ff65f - autocxx_bindgen::ir::ty::Type::layout::hfc551598363bea14
                                 at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.59.13/src/ir/ty.rs:219:9
    15:     0x55abe927cc26 - autocxx_bindgen::ir::comp::CompInfo::each_known_field_layout::h17e3d6582f1f7443
                                 at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.59.13/src/ir/comp.rs:1177:43
    16:     0x55abe927c6dd - autocxx_bindgen::ir::comp::CompInfo::layout::h0849a2c278ae1560
                                 at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.59.13/src/ir/comp.rs:1133:9
    17:     0x55abe90ff6ff - autocxx_bindgen::ir::ty::Type::layout::{{closure}}::hf92a0fb3944b649d
                                 at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.59.13/src/ir/ty.rs:221:43
    18:     0x55abe9146487 - core::option::Option<T>::or_else::h4e33cf5988a6bdb5
                                 at /build/rustc-1.56.1-src/library/core/src/option.rs:1137:21
    19:     0x55abe90ff65f - autocxx_bindgen::ir::ty::Type::layout::hfc551598363bea14
                                 at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.59.13/src/ir/ty.rs:219:9
    20:     0x55abe91e52dc - autocxx_bindgen::ir::context::BindgenContext::compute_bitfield_units::{{closure}}::h738cddd4407373e1
                                 at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.59.13/src/ir/context.rs:976:30
    21:     0x55abe91e4c17 - autocxx_bindgen::ir::context::BindgenContext::with_loaned_item::hbfcb0636609177fa
                                 at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.59.13/src/ir/context.rs:956:22
    22:     0x55abe91e5244 - autocxx_bindgen::ir::context::BindgenContext::compute_bitfield_units::h3b32622e408c018c
                                 at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.59.13/src/ir/context.rs:974:13
    23:     0x55abe91e6986 - autocxx_bindgen::ir::context::BindgenContext::gen::h5f10c8fad2e28eb8
                                 at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.59.13/src/ir/context.rs:1150:9
    24:     0x55abe91abf6e - autocxx_bindgen::codegen::codegen::h5b08a15f313f3616
                                 at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.59.13/src/codegen/mod.rs:4493:5
    25:     0x55abe90e8242 - autocxx_bindgen::Bindings::generate::he342c7d3843611d4
                                 at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.59.13/src/lib.rs:2434:32
    26:     0x55abe90e4fa3 - autocxx_bindgen::Builder::generate::h375fe9335b42969e
                                 at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-bindgen-0.59.13/src/lib.rs:1525:9
    27:     0x55abe8e757b6 - autocxx_engine::IncludeCppEngine::generate::hfb7961496eb6538f
                                 at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-engine-0.16.0/src/lib.rs:394:24
    28:     0x55abe8e5d0ae - autocxx_engine::parse_file::ParsedFile::resolve_all::h9fc4c9ad1474423b
                                 at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-engine-0.16.0/src/parse_file.rs:279:13
    29:     0x55abe8cad40b - autocxx_engine::builder::Builder<CTX>::build_listing_files::hb8efc977ae9f67df
                                 at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-engine-0.16.0/src/builder.rs:223:9
    30:     0x55abe8caf224 - autocxx_engine::builder::Builder<CTX>::build::ha2cd855e434d659a
                                 at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-engine-0.16.0/src/builder.rs:185:9
    31:     0x55abe8cac524 - autocxx_engine::builder::Builder<CTX>::expect_build::hf22d62ad64249b37
                                 at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-engine-0.16.0/src/builder.rs:272:9
    32:     0x55abe8caa77b - build_script_build::main::hff5c62058a21e758
                                 at /home/user/src/nixos/nix-ccache/nix-build-incremental/nix-build-incremental-experiments/build.rs:12:15
    33:     0x55abe8cabb3b - core::ops::function::FnOnce::call_once::hf6637bb438e2aa9a
                                 at /build/rustc-1.56.1-src/library/core/src/ops/function.rs:227:5
    34:     0x55abe8cb0cde - std::sys_common::backtrace::__rust_begin_short_backtrace::h4758ef091f3ef668
                                 at /build/rustc-1.56.1-src/library/std/src/sys_common/backtrace.rs:125:18
    35:     0x55abe8ca7d11 - std::rt::lang_start::{{closure}}::h04a1c9d2c7145c9f
                                 at /build/rustc-1.56.1-src/library/std/src/rt.rs:63:18
    36:     0x55abe97ae531 - std::rt::lang_start_internal::hc2cb966a7a4d713d
    37:     0x55abe8ca7ce0 - std::rt::lang_start::h68531eac7eac018a
                                 at /build/rustc-1.56.1-src/library/std/src/rt.rs:62:5
    38:     0x55abe8caa8ec - main
    39:     0x7fe51c879780 - __libc_start_main
    40:     0x55abe8ca7b7a - _start
                                 at /build/glibc-2.33/csu/../sysdeps/x86_64/start.S:120
    41:                0x0 - <unknown>
```

</details>

## Steps to Reproduce the Problem

https://github.com/milahu/autocxx-bug-not-an-item-itemid

```sh
# sudo apt install nix
git clone https://github.com/milahu/autocxx-bug-not-an-item-itemid
cd autocxx-bug-not-an-item-itemid
nix-shell
cargo build
```

## Specifications

- Version: 0.16.0
- Platform: linux

**Comment by adetaylor** [comment]
Thanks for the report!

From the stack trace, this looks like a problem in `autocxx-bindgen`, which is the fork of `bindgen` that is used inside `autocxx`. The next step is to figure out if this is a problem with upstream `bindgen` itself.

Please could you run `touch build.rs; AUTOCXX_REPRO_CASE=repro.json cargo build` and then attach `repro.json` here? It will be a huge file with a preprocessed version of all the headers.

If things go well, I can feed that into `creduce` and get a minimal test case which we can try against `bindgen` and possibly report to them.

If things don't go well, I will give you instructions to run the same `creduce` procedure.

**Comment by milahu** [comment]
now with `AUTOCXX_REPRO_CASE=repro.json` i also see this warning

```
  /run/user/1000/.tmpD8kJRF:53:9: warning: #pragma once in main file
     53 | #pragma once
        |         ^~~~
```

[repro.json.gz](https://github.com/google/autocxx/files/8030163/repro.json.gz)

**Comment by adetaylor** [comment]
I don't have any immediate solutions. You're the first person trying to use `autocxx-reduce` apart from me, as far as I know, so I'm not surprised you run into some problems.

Here are my minimal notes on how typically to run it: https://github.com/google/autocxx/blob/main/tools/reduce/README.md

When I get it running though, it does manage to get there in the end and emits a tiny test case. It usually takes 3-4 days on a 192 core machine.

**Comment by milahu** [comment]
> It usually takes 3-4 days on a 192 core machine.

thats crazy. i have 2 cores so ... 1 year : D

now running `halfempty` ...

```
Input file "/run/user/1000/tmp.nXeWTMjOTy.halfempty.h" is now 3100614 bytes, starting strategy "bisect"...
Verifying the original input executes successfully... (skip with --noverify)
The original input file succeeded after 19.0 seconds.
New finalized size: 3100614 (depth=2) real=0.0s, user=0.0s, speedup=~-0.0s
New finalized size: 2325461 (depth=9) real=27.2s, user=65.0s, speedup=~37.8s
New finalized size: 2277014 (depth=98) real=232.4s, user=662.6s, speedup=~430.2s
New finalized size: 2252791 (depth=176) real=407.1s, user=1147.8s, speedup=~740.6s
New finalized size: 2228568 (depth=191) real=440.2s, user=1214.0s, speedup=~773.8s
New finalized size: 2204345 (depth=192) real=456.2s, user=1229.9s, speedup=~773.7s
New finalized size: 2192234 (depth=201) real=484.9s, user=1301.2s, speedup=~816.4s
New finalized size: 2180123 (depth=231) real=551.0s, user=1468.8s, speedup=~917.9s
New finalized size: 2168012 (depth=248) real=586.9s, user=1551.0s, speedup=~964.0s
```

<details>
<summary>halfempty.sh</summary>

```sh
#! /bin/sh

set -eu

repro_json=repro-musl.json

header_file=$(mktemp --suffix=.halfempty.h)
echo "header_file = $header_file"
jq -r .header <"$repro_json" >"$header_file"

# TODO -I. ?
cxx="g++ -O0 -x c++ -std=c++14 -DBINDGEN -I. -c"

autocxx_gen="/home/user/src/nixos/nix-ccache/nix-build-incremental/nix-build-incremental-experiments/autocxx/target/debug/autocxx-gen"

# create_rs_file in autocxx/tools/reduce/src/main.rs
# user-defined directives after #include "concat.h"
input_rs=$(mktemp --suffix=.halfempty.rs)
cat >"$input_rs" <<EOF
use autocxx::include_cpp;
include_cpp!(
  #include "concat.h"
  safety!(unsafe)
  generate!("clang::tooling::CommonOptionsParser")
);
EOF

test_script=$(mktemp --suffix=.halfempty.sh)
echo "test_script = $header_file"
# halfempty: input = /dev/stdin
# result 0 -> ok
# result 1 -> fail
cat >"$test_script" <<EOF
#! /bin/sh
set -e # exit on error
set -x # xtrace
result=1
temp_dir=\$(mktemp -d)
trap 'rm -rf \$temp_dir; exit \$result' EXIT TERM ALRM

cat > \$temp_dir/concat.h # read from stdin

# does it compile?
$cxx \$temp_dir/concat.h -o /dev/null

mv \$temp_dir/concat.h \$temp_dir/concat-body.h

# codegen
# does it produce the error?

# TODO why this wrapper?
cat > \$temp_dir/concat.h <<'EOF2'
#ifndef __CONCAT_H__
#define __CONCAT_H__
#include "concat-body.h"
#endif
EOF2

export LIBCLANG_PATH="/nix/store/qjvrbibnrh1hdba5f68kwa4wa7nbvhyq-clang-10.0.1-lib/lib"

# TODO why "cat gen.complete.rs" etc?

(
  "$autocxx_gen" \
  -o \$temp_dir \
  -I \$temp_dir \
  "$input_rs" \
  --gen-rs-complete \
  --gen-cpp \
  --suppress-system-headers \
  -- \
  2>&1 \
  && \
  cat gen.complete.rs \
  && \
  cat autocxxgen*.h \
  && \
  $cxx gen0.cc 2>&1
) | grep "^thread 'main' panicked at 'Not an item: ItemId" && { result=0; }
EOF
chmod +x "$test_script"



# https://github.com/googleprojectzero/halfempty

exec halfempty --zero-char=0x20 --gen-intermediate "$test_script" "$header_file"
```

</details>

micro optimizations:

* `gcc -O0`
* store tempfiles in ram = `/run/user/1000/`
* maybe skip the "does it compile?" step. takes long, is done by `autocxx-gen` anyway (?)

**Comment by adetaylor** [comment]
> thats crazy

Yeah, it's also incredibly loud :)

> maybe skip the "does it compile?" step. takes long, is done by autocxx-gen anyway (?)

The pre-compile step is because `clang` is faster at rejecting invalid code than `autocxx-gen`, so this seemed to be a net saving.

If you can get any `autocxx-reduce` command _starting_ to run successfully (i.e. the interestingness test seems to be doing the right thing), send me the `repro.json` and the command you used, and I'll get it running on my machine.

**Comment by milahu** [comment]
4 MB -> 1.3 MB : )

[halfempty.out.gz](https://github.com/google/autocxx/files/8036857/halfempty.out.gz)

you will need to patch `LIBCLANG_PATH` and `autocxx_gen`

**Comment by adetaylor** [comment]
It seems to be running happily with this command:

> `~/autocxx/halfempty$ ../target/release/autocxx-reduce --problem 'Not an item' -k --creduce-arg=--n  --creduce-arg=192 file --header halfempty.h  -I. --directive 'generate!("clang::tooling::CommonOptionsParser::create")'`

(and astonishingly fast by its normal standards, hopefully will be done in a few minutes!)

**Comment by adetaylor** [comment]
```cpp
namespace {
namespace {
template <typename> union a { a b; };
} // namespace
} // namespace
```

Next step is to feed that to regular bindgen. I'm unlikely to get to that today. If you get there first, the autocxx logging will print out the command-line args it feeds to bindgen, so it would be worth getting that first. (`RUST_LOG=autocxx_engine=info cargo build -vvv`).

**Comment by milahu** [comment]
thats the reduced code? makes no sense, does not compile `error: field ‘b’ has incomplete type`

**Comment by milahu** [comment]
the mysterious `b` is probably a destructor

```cc
template <typename> union a { a b; };
```

could be reduced from [llvm/Support/type_traits.h](https://github.com/llvm/llvm-project/blob/llvmorg-10.0.1/llvm/include/llvm/Support/type_traits.h#L75) in the namespace `llvm::detail::`

```cc
// grep -A5 -E 'template.*typename.*union.*{' repro-musl.json.hh
// grep -E -e 'template.*typename.*union.*{' -e '^# ' repro-musl.json.hh | grep -B1 -E 'template.*typename.*union.*{'

# 19 "/nix/store/mck6a026qp4ydzkz9wn6ww2npnjmidlx-llvm-10.0.1-dev/include/llvm/Support/type_traits.h" 2 3 4
template<typename T> union copy_construction_triviality_helper {
    T t;
    copy_construction_triviality_helper() = default;
    copy_construction_triviality_helper(const copy_construction_triviality_helper&) = default;
    ~copy_construction_triviality_helper() = default;
};

# 19 "/nix/store/mck6a026qp4ydzkz9wn6ww2npnjmidlx-llvm-10.0.1-dev/include/llvm/Support/type_traits.h" 2 3 4
template<typename T> union move_construction_triviality_helper {
    T t;
    move_construction_triviality_helper() = default;
    move_construction_triviality_helper(move_construction_triviality_helper&&) = default;
    ~move_construction_triviality_helper() = default;
};
```

these are used in

```cc
// llvm/Support/type_traits.h

/// An implementation of `std::is_trivially_copy_constructible` since we have
/// users with STLs that don't yet include it.
template <typename T>
struct is_trivially_copy_constructible
    : std::is_copy_constructible<
          ::llvm::detail::copy_construction_triviality_helper<T>> {};

/// An implementation of `std::is_trivially_move_constructible` since we have
/// users with STLs that don't yet include it.
template <typename T>
struct is_trivially_move_constructible
    : std::is_move_constructible<
          ::llvm::detail::move_construction_triviality_helper<T>> {};
```

https://en.cppreference.com/w/cpp/types/is_copy_constructible

> If an instantiation of a template above depends, directly or indirectly, on an **incomplete type**, and that instantiation could yield a different result if that type were hypothetically completed, the behavior is undefined.

> ... `is_trivially_copy_constructible`, which, in these implementations, also requires that the destructor is trivial
