### ISSUE TITLE
Figure out how to run ASAN over tests

### ISSUE THREAD

**Issue by adetaylor** [google/autocxx#844]
Especially with the changes in #766 and similar, we're starting to manage object allocations a little bit within autocxx not just defer them to cxx.

It would be good to see if we can figure out how to run our examples under [address sanitizer](https://doc.rust-lang.org/beta/unstable-book/compiler-flags/sanitizer.html). This is likely to require a matching LLVM version between clang and rustc, as well as compiling both the Rust and C++ bits of each test case with ASAN.

**Comment by philipcraig** [comment]
Working on this

**Comment by adetaylor** [comment]
Experiments running ASAN on Linux (not on the tests, yet)

Revision 9f3bf7e2a4734bc56d5b4c7827dccf6fbb64b944 (part of #742)

Plus this patch:

```
diff --git a/demo/build.rs b/demo/build.rs
index 9a16a34b..7c8f7ef3 100644
--- a/demo/build.rs
+++ b/demo/build.rs
@@ -9,7 +9,7 @@
 fn main() -> miette::Result<()> {
     let path = std::path::PathBuf::from("src");
     let mut b = autocxx_build::Builder::new("src/main.rs", &[&path]).build()?;
-    b.flag_if_supported("-std=c++14").compile("autocxx-demo");
+    b.flag_if_supported("-std=c++14").flag_if_supported("-fsanitize=address").compile("autocxx-demo");
 
     println!("cargo:rerun-if-changed=src/main.rs");
     println!("cargo:rerun-if-changed=src/input.h");
```

when run this way:

```
~/autocxx2/demo$ CFLAGS="-fsanitize=address" RUSTFLAGS="-Z sanitizer=address -Clink-arg=-fuse-ld=lld -Clink-arg=-fsanitize=address" cargo run -Z build-std --target=x86_64-unknown-linux-gnu
```

gives this delightful overflow report:

```
=================================================================
==1573955==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000000030 at pc 0x55b136ea358b bp 0x7ffe8def7080 sp 0x7ffe8def7078
WRITE of size 4 at 0x602000000030 thread T0
    #0 0x55b136ea358a in Goat::Goat() /usr/local/google/home/adetaylor/autocxx2/demo/src/input.h:30:16
    #1 0x55b136ea3beb in new_autocxx_autocxx_wrapper(Goat*) /usr/local/google/home/adetaylor/autocxx2/target/x86_64-unknown-linux-gnu/debug/build/autocxx-demo-5c43dfa3cfcfd8da/out/autocxx-build-dir/include/autocxxgen_ffi.h:42:96
    #2 0x55b136ea3ef1 in cxxbridge1$new_autocxx_autocxx_wrapper /usr/local/google/home/adetaylor/autocxx2/target/x86_64-unknown-linux-gnu/debug/build/autocxx-demo-5c43dfa3cfcfd8da/out/autocxx-build-dir/cxx/gen0.cxx:142:31
    #3 0x55b136e9f90b in autocxx_demo::ffi::cxxbridge::new_autocxx_autocxx_wrapper::h4af0f94d5efe56ac /usr/local/google/home/adetaylor/autocxx2/target/x86_64-unknown-linux-gnu/debug/build/autocxx-demo-5c43dfa3cfcfd8da/out/autocxx-build-dir/rs/autocxx-ffi-default-gen.rs:1:3025
    #4 0x55b136e9ec3e in autocxx_demo::ffi::bindgen::root::Goat::new::_$u7b$$u7b$closure$u7d$$u7d$::h9a12523f83c47032 /usr/local/google/home/adetaylor/autocxx2/target/x86_64-unknown-linux-gnu/debug/build/autocxx-demo-5c43dfa3cfcfd8da/out/autocxx-build-dir/rs/autocxx-ffi-default-gen.rs:1:1447
    #5 0x55b136ea2d65 in _$LT$moveit..new..factories..by_raw..FnNew$LT$F$C$T$GT$$u20$as$u20$moveit..new..New$GT$::new::h1c51a4afc6740cb1 /usr/local/google/home/adetaylor/.cargo/registry/src/github.com-1ecc6299db9ec823/moveit-0.5.0/src/new/factories.rs:50:7
    #6 0x55b136ea2d2d in _$LT$N$u20$as$u20$moveit..new..TryNew$GT$::try_new::h0ecb34d7d587b3b5 /usr/local/google/home/adetaylor/.cargo/registry/src/github.com-1ecc6299db9ec823/moveit-0.5.0/src/new/mod.rs:140:5
    #7 0x55b136ea1393 in moveit::cxx_support::_$LT$impl$u20$moveit..new..EmplaceUnpinned$LT$T$GT$$u20$for$u20$cxx..unique_ptr..UniquePtr$LT$T$GT$$GT$::try_emplace::h4a11107d29c18fc3 /usr/local/google/home/adetaylor/.cargo/registry/src/github.com-1ecc6299db9ec823/moveit-0.5.0/src/cxx_support.rs:72:20
    #8 0x55b136ea1874 in moveit::new::EmplaceUnpinned::emplace::hd9c649da1ff9be1c /usr/local/google/home/adetaylor/.cargo/registry/src/github.com-1ecc6299db9ec823/moveit-0.5.0/src/new/mod.rs:168:11
    #9 0x55b136ea0572 in autocxx_demo::ffi::bindgen::root::Goat::make_unique::h16d0f191a4bdce3e /usr/local/google/home/adetaylor/autocxx2/target/x86_64-unknown-linux-gnu/debug/build/autocxx-demo-5c43dfa3cfcfd8da/out/autocxx-build-dir/rs/autocxx-ffi-default-gen.rs:1:1221
    #10 0x55b136e9efad in autocxx_demo::main::hc8b7732277fffe3e /usr/local/google/home/adetaylor/autocxx2/demo/src/main.rs:19:20
    #11 0x55b136e9fdca in core::ops::function::FnOnce::call_once::h8312cc58750e101d /usr/local/google/home/adetaylor/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
    #12 0x55b136ea2af4 in std::sys_common::backtrace::__rust_begin_short_backtrace::h6fa79af7861962a1 /usr/local/google/home/adetaylor/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:122:18
    #13 0x55b136ea27b3 in std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::h9faa8862bd20e201 /usr/local/google/home/adetaylor/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:145:18
    #14 0x55b1370c148d in core::ops::function::impls::_$LT$impl$u20$core..ops..function..FnOnce$LT$A$GT$$u20$for$u20$$RF$F$GT$::call_once::h7125726fb50de5b4 /usr/local/google/home/adetaylor/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:259:13
    #15 0x55b13717483e in std::panicking::try::do_call::h3289707f8aceb879 /usr/local/google/home/adetaylor/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:492:40
    #16 0x55b137185b9a in __rust_try std.a87d9858-cgu.8
    #17 0x55b137172e52 in std::panicking::try::h0a6a01f4f201c8ba /usr/local/google/home/adetaylor/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:456:19
    #18 0x55b136f5c5e9 in std::panic::catch_unwind::h1f9b631bc58e08e0 /usr/local/google/home/adetaylor/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:137:14
    #19 0x55b136fa430b in std::rt::lang_start_internal::_$u7b$$u7b$closure$u7d$$u7d$::h1ab18e5021f6c521 /usr/local/google/home/adetaylor/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:128:48
    #20 0x55b137174bcd in std::panicking::try::do_call::hffa94f92ce4f2ea2 /usr/local/google/home/adetaylor/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:492:40
    #21 0x55b137185b9a in __rust_try std.a87d9858-cgu.8
    #22 0x55b137173ebb in std::panicking::try::hb99c4f920ccdf55e /usr/local/google/home/adetaylor/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:456:19
    #23 0x55b136f5c789 in std::panic::catch_unwind::he8aaf945a746d5a2 /usr/local/google/home/adetaylor/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:137:14
    #24 0x55b136fa3c49 in std::rt::lang_start_internal::h3eab8a1bf682e706 /usr/local/google/home/adetaylor/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:128:20
    #25 0x55b136ea2715 in std::rt::lang_start::hb69a756b2f239727 /usr/local/google/home/adetaylor/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:144:17
    #26 0x55b136e9f6ab in main (/usr/local/google/home/adetaylor/autocxx2/target/x86_64-unknown-linux-gnu/debug/autocxx-demo+0x1df6ab) (BuildId: e4aba58d79771bfc)
    #27 0x7fdb625437fc in __libc_start_main csu/../csu/libc-start.c:332:16
    #28 0x55b136e03919 in _start (/usr/local/google/home/adetaylor/autocxx2/target/x86_64-unknown-linux-gnu/debug/autocxx-demo+0x143919) (BuildId: e4aba58d79771bfc)

0x602000000031 is located 0 bytes to the right of 1-byte region [0x602000000030,0x602000000031)
allocated by thread T0 here:
    #0 0x55b136e7698e in malloc /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:69:3
    #1 0x7fdb6292681b in operator new(unsigned long) (/lib/x86_64-linux-gnu/libstdc++.so.6+0xa981b) (BuildId: b481c8337312c14a599624014abeec8714dd8cf1)
    #2 0x55b136ea416c in Goat* new_appropriately<Goat>(unsigned long) /usr/local/google/home/adetaylor/autocxx2/target/x86_64-unknown-linux-gnu/debug/build/autocxx-demo-5c43dfa3cfcfd8da/out/autocxx-build-dir/include/autocxxgen_ffi.h:29:37
    #3 0x55b136ea39dd in Goat_alloc_autocxx_wrapper() /usr/local/google/home/adetaylor/autocxx2/target/x86_64-unknown-linux-gnu/debug/build/autocxx-demo-5c43dfa3cfcfd8da/out/autocxx-build-dir/include/autocxxgen_ffi.h:39:76
    #4 0x55b136ea3c2f in cxxbridge1$Goat_alloc_autocxx_wrapper /usr/local/google/home/adetaylor/autocxx2/target/x86_64-unknown-linux-gnu/debug/build/autocxx-demo-5c43dfa3cfcfd8da/out/autocxx-build-dir/cxx/gen0.cxx:122:37
    #5 0x55b136e9f6c9 in autocxx_demo::ffi::cxxbridge::Goat_alloc_autocxx_wrapper::ha1c725e784282039 /usr/local/google/home/adetaylor/autocxx2/target/x86_64-unknown-linux-gnu/debug/build/autocxx-demo-5c43dfa3cfcfd8da/out/autocxx-build-dir/rs/autocxx-ffi-default-gen.rs:1:2719
    #6 0x55b136ea1874 in moveit::new::EmplaceUnpinned::emplace::hd9c649da1ff9be1c /usr/local/google/home/adetaylor/.cargo/registry/src/github.com-1ecc6299db9ec823/moveit-0.5.0/src/new/mod.rs:168:11
    #7 0x55b136ea0572 in autocxx_demo::ffi::bindgen::root::Goat::make_unique::h16d0f191a4bdce3e /usr/local/google/home/adetaylor/autocxx2/target/x86_64-unknown-linux-gnu/debug/build/autocxx-demo-5c43dfa3cfcfd8da/out/autocxx-build-dir/rs/autocxx-ffi-default-gen.rs:1:1221
    #8 0x55b136e9efad in autocxx_demo::main::hc8b7732277fffe3e /usr/local/google/home/adetaylor/autocxx2/demo/src/main.rs:19:20
    #9 0x55b136e9fdca in core::ops::function::FnOnce::call_once::h8312cc58750e101d /usr/local/google/home/adetaylor/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
    #10 0x55b136ea27b3 in std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::h9faa8862bd20e201 /usr/local/google/home/adetaylor/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:145:18
    #11 0x55b13717483e in std::panicking::try::do_call::h3289707f8aceb879 /usr/local/google/home/adetaylor/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:492:40
    #12 0x55b137185b9a in __rust_try std.a87d9858-cgu.8
    #13 0x55b136f5c5e9 in std::panic::catch_unwind::h1f9b631bc58e08e0 /usr/local/google/home/adetaylor/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:137:14
    #14 0x55b136fa430b in std::rt::lang_start_internal::_$u7b$$u7b$closure$u7d$$u7d$::h1ab18e5021f6c521 /usr/local/google/home/adetaylor/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:128:48
    #15 0x55b137174bcd in std::panicking::try::do_call::hffa94f92ce4f2ea2 /usr/local/google/home/adetaylor/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:492:40
    #16 0x55b137185b9a in __rust_try std.a87d9858-cgu.8
    #17 0x55b136f5c789 in std::panic::catch_unwind::he8aaf945a746d5a2 /usr/local/google/home/adetaylor/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:137:14
    #18 0x55b136fa3c49 in std::rt::lang_start_internal::h3eab8a1bf682e706 /usr/local/google/home/adetaylor/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:128:20
    #19 0x55b136ea2715 in std::rt::lang_start::hb69a756b2f239727 /usr/local/google/home/adetaylor/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:144:17
    #20 0x55b136e9f6ab in main (/usr/local/google/home/adetaylor/autocxx2/target/x86_64-unknown-linux-gnu/debug/autocxx-demo+0x1df6ab) (BuildId: e4aba58d79771bfc)

SUMMARY: AddressSanitizer: heap-buffer-overflow /usr/local/google/home/adetaylor/autocxx2/demo/src/input.h:30:16 in Goat::Goat()
Shadow bytes around the buggy address:
  0x0c047fff7fb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7fc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7fd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7fe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7ff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c047fff8000: fa fa 05 fa fa fa[01]fa fa fa fa fa fa fa fa fa
  0x0c047fff8010: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8020: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8030: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8040: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8050: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==1573955==ABORTING
```

**Comment by adetaylor** [comment]
Pretty sure goats should never be one byte long.

🐐
